# Archivo de configuración para conectarnos al backend S3 de STAGE
# Se usa corriendo: terraform init -backend-config=backend-stage.conf

bucket         = "demo-ticketing-tfstate-operations-stage"
key            = "demo-ticketing-auth-backend/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "demo-ticketing-tfstate-lock-stage"
encrypt        = true
# Como el bucket vive en la cuenta operations-stage (772385118422) y desde local estamos en la Management account,
# necesitamos decirle al backend S3 (al momento del init) que asuma el rol hacia Operations para poder escrbir.
role_arn       = "arn:aws:iam::772385118422:role/OrganizationAccountAccessRole"
