# Archivo de configuración para conectarnos al backend S3 de PROD
# Se usa corriendo: terraform init -backend-config=backend-prod.conf

bucket         = "demo-ticketing-tfstate-operations-prod"
key            = "demo-ticketing-auth-backend/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "demo-ticketing-tfstate-lock-prod"
encrypt        = true
# Como el bucket vive en la cuenta operations-prod (863942760652) y desde local estamos en la Management account,
# necesitamos decirle al backend S3 (al momento del init) que asuma el rol hacia Operations para poder escrbir.
role_arn       = "arn:aws:iam::863942760652:role/OrganizationAccountAccessRole"
